FROM debian

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git

## ------ Usage --------
# docker build -t bonus02 .
# docker run --rm -ti bonus02

## ------ Testing --------
# echo "#include <stdio.h>
# int main(){
#  printf("\""Hello World\n"\"");
# return (0);
# }
# " >> hello.c
