FROM debian

RUN apt-get update && apt-get install -y toilet

CMD ["bash"]

## ------ Usage --------
# docker build -t bonus03 .
# docker run -it bonus03

## ------ Testing --------
# toilet -f future Hello World --filter flip
# font path: /usr/share/figlet